name: 'HGD'
n_classes: 4
n_subs: 14
n_chans: 22
in_samples: 1125
classes_labels: ['feet', 'left_hand', 'rest', 'right_hand']
data_path: 'D:/dataset/BCI/HGD/'
LOSO: False
standardized: True
shuffle: True
one_hot: False